FROM    alpine:latest AS builder
RUN     [ "apk", "add", "--no-cache", "gcc", "make", "musl-dev", "git" ]
WORKDIR /build
COPY    . .
RUN     [ "make", "clean", "static" ]

# just an example
FROM       alpine:latest
COPY       --from=builder /build/run /bin/run
# CMD ["/bin/run", "-g", "your-service"]
