#!/bin/sh -e

SCRIPT="$(basename "$0")"

die() {
	echo >&2 "$SCRIPT: [error]" "$@"
	exit 1
}

log() {
	echo >&2 "$SCRIPT: [info]" "$@"
}

RUN="docker run --network none"

# docker image
IMAGE="${1:?missing image name}"

# cleanup
cleanup() {
    log "cleaning up..."
	IDS="$(docker ps -aqf "ancestor=$IMAGE")"
	[ -z "$IDS" ] || docker rm -f "$IDS"
	log "all done."
}

trap cleanup EXIT
trap 'die "interrupted!"' INT TERM HUP QUIT

# test runner
TOTAL=0

test_case() {
	TOTAL=$((TOTAL + 1))
	log "test $TOTAL: $1"
	sh || die 'FAILED'
	log 'passed'
}

# test cases
test_case 'version' <<-EOF
	! $RUN --rm $IMAGE -v
EOF

test_case 'simple invocation' <<-EOF
	$RUN --rm $IMAGE sleep 0.1
EOF

test_case 'simple error propagation' <<-EOF
	$RUN --rm $IMAGE sh -c 'exit 42'
	[ \$? -eq 42 ]
EOF

test_case 'invalid command' <<-EOF
    ! $RUN --rm $IMAGE nonexistent-command
EOF

test_case 'recursive error propagation' <<-EOF
	$RUN --rm $IMAGE /bin/run /bin/run sh -c 'exit 42'
	[ \$? -eq 42 ]
EOF

test_case 'two processes, normal mode' <<-EOF
	$RUN --rm $IMAGE -s TERM sh -ec 'sleep 0.2 & sleep 0.1'
	[ \$? -eq 143 ]
EOF

test_case 'two processes, daemon mode' <<-EOF
	$RUN --rm $IMAGE -ds TERM sh -ec 'sleep 0.2 & sleep 0.1'
EOF

test_case 'two processes, daemon mode, with shell error' <<-EOF
	$RUN --rm $IMAGE -ds TERM sh -ec 'sleep 0.2 & sleep 0.1 ; exit 42'
	[ \$? -eq 143 ]
EOF

test_case 'two processes, daemon mode, with daemon error' <<-EOF
	$RUN --rm $IMAGE -ds TERM sh -ec '( ! sleep 0.1 & ) ; sleep 0.5'
	[ \$? -eq 143 ]
EOF

test_case 'docker stop' <<-EOF
	set -e
	CID=\$($RUN -d $IMAGE -s HUP sh -ec 'trap '\''echo Stopping'\'' TERM; sleep 1 ; exit 42')
	trap 'docker rm -f "\$CID" >/dev/null' EXIT
	sleep 0.2
	docker stop -t 3 "\$CID" >/dev/null
	RET="\$(docker wait "\$CID")"
	[ \$RET -eq 143 ]
    docker logs "\$CID" | grep -q 'Stopping'
EOF

test_case 'STDIN handling' <<-EOF
    echo 'hello world' | $RUN --rm -i $IMAGE cat | grep -q 'hello world'
EOF

test_case 'auto-stop' <<-EOF
	$RUN --rm $IMAGE -s HUP sh -ec 'sleep 1 & sleep 0.5'
	[ \$? -eq 129 ]
EOF

test_case 'auto-stop then kill' <<-EOF
	$RUN --rm $IMAGE -s HUP -t 1 sh -ec 'nohup sleep 2 & sleep 0.5'
	[ \$? -eq 137 ]
EOF

test_case 'SIGALRM propagation' <<-EOF
	$RUN --rm $IMAGE sh -ec 'sleep 2 & sleep 0.5 ; kill -ALRM 1'
	[ \$? -eq 142 ]
EOF

log "completed $TOTAL test cases"
